### ISSUE TITLE
enum error with MakeCode beta

### ISSUE THREAD

**Issue by belmont-admin** [KitronikLtd/pxt-kitronik-game-controller#1]
There seems to be a problem with the :GAME Controller when used with MakeCode beta. The problem does not exhibit itself when using the release version of MakeCode. 

The problem seems to be on line 24 of the controller.ts file:

```
  22 export enum ControllerButtonPins {
  23      //% block="Joypad Up (P8)"
  24      Up = <number>DAL.MICROBIT_ID_IO_P8,  // This is the only line with <number>
  25      //% block="Joypad Down (P14)"
  26      Down = DAL.MICROBIT_ID_IO_P14,
  27      //% block="Joypad Left (P12)"
  28      Left = DAL.MICROBIT_ID_IO_P12,
  29      //% block="Joypad Right (P13)"
  30      Right = DAL.MICROBIT_ID_IO_P13,
  31      //% block="Fire 1 (P15)"
  32      Fire1 = DAL.MICROBIT_ID_IO_P15,
  33      //% block="Fire 2 (P16)"
  34      Fire2 = DAL.MICROBIT_ID_IO_P16
```
In the MakeCode beta blocks editor the JoyPad Up Pin8 block shows and error 'Cannot compute enum value' 

![Screenshot 2019-12-22 at 18 23 05](https://user-images.githubusercontent.com/58621487/71325693-27fb1380-24e8-11ea-87c9-49c70fa93629.png)

**Comment by AlasdairAtKitronik** [comment]
Thank you for identifying this issue, the problem has now been fixed and tested in MakeCode beta.
