### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [KitronikLtd/pxt-kitronik-game-controller#2]
Hi @KitronikLtd,

As you might have seen from microsoft/pxt-microbit#3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer.

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit here (lancaster-university/codal-microbit-v2#31).

Looking at your extension source I believe that your extension falls under this category:

> Use of mbed APIs that are not included in the compatibility layer, or microbit-dal APIs that need different constructors

**Comment by KitronikLtd** [comment]
@microbit-sam I opened an issue about this some time ago, and have had no help as to how to go about fixing the issue:
https://github.com/microsoft/pxt-microbit/issues/3532
What is required to switch to the new button stuff?

**Comment by AlasdairAtKitronik** [comment]
@microbit-sam This has become a more major concern now, as it appears V3 MakeCode has gone live (with barely any notice). I had hoped the button thing would just work like you'd hoped, but when I try to download, MakeCode just hangs (presumably forever, it's been several mins now) with this:
![image](https://user-images.githubusercontent.com/36475405/99791270-4e249b80-2b1d-11eb-9f25-d209e1645566.png)

**Comment by microbit-sam** [comment]
Same issue in https://github.com/KitronikLtd/pxt-kitronik-zip-64/issues/2, will track there if that's ok so we don't have to repeat ourselves

**Comment by AlasdairAtKitronik** [comment]
> Same issue in [KitronikLtd/pxt-kitronik-zip-64#2](https://github.com/KitronikLtd/pxt-kitronik-zip-64/issues/2), will track there if that's ok so we don't have to repeat ourselves

No problem

**Comment by AlasdairAtKitronik** [comment]
:GAME Controller now works correctly with V2 micro:bit.
