### ISSUE TITLE
How to import into makecode?

### ISSUE THREAD

**Issue by Swmboy** [KitronikLtd/pxt-kitronik-game-controller#3]
How do I import and use this in makecode?

**Comment by DaveAtKitronik** [comment]
Press Extensions:

![image](https://user-images.githubusercontent.com/25896029/235081734-52e92360-e0d5-4e6d-914f-a53c9b780c17.png)

Type kitronik game in the search bar:

![image](https://user-images.githubusercontent.com/25896029/235081966-6632fff9-3372-4ce5-addc-7bb56fdf2581.png)

Press the game controller image:

![image](https://user-images.githubusercontent.com/25896029/235082058-246c0221-de83-4ed6-9f90-d30ac9d5b786.png)

blocks appear in the pallet:

![image](https://user-images.githubusercontent.com/25896029/235082227-e4f3cede-3d11-43cd-ad9d-92cb2be772dd.png)

The blocks are similar to the On Button A pressed block - where you can trigger some code when the button is pressed, or a sub block you can drop inot other blocks (like an if block) 

![image](https://user-images.githubusercontent.com/25896029/235082695-622debd5-3c09-43f4-8577-365e233bff40.png)

You need to set the pitch pin to buzzer in on start to make the buzzer use the music blocks.:

![image](https://user-images.githubusercontent.com/25896029/235082965-6052d02a-c492-40f3-9f8d-0b19cc64e661.png)

**Comment by Swmboy** [comment]
No I mean directly importing it. I'm using brilliantlabs (literally the same as makecode except it uses a special microbit board) it does not have the addon, but it has the import addon feature. If you could tell me how to compile this then import it into that, it would be greatly appreciated 

Thanks

**Comment by DaveAtKitronik** [comment]
The BrillaintLabs editor is customised makecode only for use with the b.board, or a stand alone micro:bit. It cannot as far as I can tell be used with any other micro:bit add ons.

If you have our board and a micro:bit you should use the micro:bit makecode editor (https://makecode.microbit.org/) and import our extension into that.

**Comment by Swmboy** [comment]
Oh alright. Do you know of any microbit controllers compatible with the b board?
Thanks

**Comment by DaveAtKitronik** [comment]
I dont understand? 
The b.board appears to take a normal micro:bit and then lock you into their walled garden.
If you want to use the micro:bit with other accessories then unplug it from the b board, plug it into what ever accessory you have and use the standard makecode editor to write the code.
If you have to use b board editor for some reason (school locked IT for instance) then you are stuck with what ever brilliant labs will provide - maybe ask them.
